name: push
on: push
jobs:
  BuildAndTest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: dotnet build PowerCollections/PowerCollections
      - name: Test
        run: dotnet test PowerCollections/PowerCollections.Tests